apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sample-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
    limits:
      storage: 5Gi