apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}-app-hpa
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: {{ .Values.appHpa.minReplicas }}
  maxReplicas: {{ .Values.appHpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.appHpa.targetCPUUtilizationPercentage }}
