apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-cron-job
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args: {{- toYaml .Values.cronJob.hello.args | nindent 12 }}
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            env:
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            image: {{ .Values.cronJob.hello.image.repository }}:{{ .Values.cronJob.hello.image.tag
              | default .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.cronJob.hello.imagePullPolicy }}
            name: hello
            resources: {}
          restartPolicy: OnFailure
  schedule: {{ .Values.cronJob.schedule | quote }}