apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "app.fullname" . }}-fluentd-elasticsearch
  labels:
    k8s-app: fluentd-logging
  {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
    {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
      {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      fluentdElasticsearch:
        fluentdElasticsearch:
          image:
            repository: quay.io/fluentd_elasticsearch/fluentd
            tag: v2.5.2
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi