apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-my-sample-pv-claim
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    limits:
      storage: {{ tpl (.Values.pvc.mySamplePvClaim.storageLimit) $ | quote }}
    requests:
      storage: {{ tpl (.Values.pvc.mySamplePvClaim.storageRequest) $ | quote }}
  storageClassName: {{ tpl (.Values.pvc.mySamplePvClaim.storageClass) $ | quote }}