apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-my-secret-vars
  labels:
  {{- include "app.labels" . | nindent 4 }}
data:
  ELASTIC_FOOBAR_HUNTER123_MEOWTOWN_VERIFY: {{ required "mySecretVars.elasticFoobarHunter123MeowtownVerify is required" .Values.mySecretVars.elasticFoobarHunter123MeowtownVerify | b64enc
    | quote }}
  VAR1: {{ required "mySecretVars.var1 is required" .Values.mySecretVars.var1 | b64enc
    | quote }}
  VAR2: {{ required "mySecretVars.var2 is required" .Values.mySecretVars.var2 | b64enc
    | quote }}
stringData:
  str: {{ required "mySecretVars.str is required" .Values.mySecretVars.str | quote
    }}
type: opaque