apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-nginx
  labels:
    app: nginx
  {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.type }}
  selector:
    app: nginx
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.nginx.ports | toYaml | nindent 2 }}