apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret-vars
  labels:
  {{- include "app.labels" . | nindent 4 }}
data:
  ELASTIC_FOOBAR_HUNTER123_MEOWTOWN_VERIFY: {{ required "secretVars.elasticFoobarHunter123MeowtownVerify is required" .Values.secretVars.elasticFoobarHunter123MeowtownVerify | b64enc
    | quote }}
  VAR1: {{ required "secretVars.var1 is required" .Values.secretVars.var1 | b64enc
    | quote }}
  VAR2: {{ required "secretVars.var2 is required" .Values.secretVars.var2 | b64enc
    | quote }}
stringData:
  str: {{ required "secretVars.str is required" .Values.secretVars.str | quote }}
type: opaque
