apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}-web
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: nginx
  serviceName: {{ include "app.fullname" . }}-nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.web.nginx.image.repository }}:{{ .Values.web.nginx.image.tag
          | default .Chart.AppVersion }}
        name: nginx
        ports:
        - containerPort: 80
          name: web
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
      nodeSelector: {{- toYaml .Values.web.nodeSelector | nindent 8 }}
      serviceAccountName: {{ default "default" (include "app.serviceAccountName" .)
        }}
      tolerations: {{- toYaml .Values.web.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.web.topologySpreadConstraints |
        nindent 8 }}
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources: {{ .Values.web.volumeClaims.www | toYaml | nindent 8 }}
