configmapVars:
  var4: value for var4
controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.8.0
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
    env:
      var2: ciao
      var3MyEnv: ciao
    image:
      repository: controller
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 20Mi
  nodeSelector: {}
  replicas: 1
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerManagerConfigYaml: |-
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 3a2e09e9.example.com
    rook:
      namespace: rook-ceph
      toolboxPodLabel: rook-ceph-tools
  dummyconfigmapkey: dummyconfigmapvalue
metricsService:
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
pvc:
  pvcLim:
    storageClass: cust1-mypool-lim
    storageRequest: 2Gi
secretCa:
  caCrt: ""
secretRegistryCredentials:
  dockerconfigjson: ""
secretVars:
  var1: ""
  var2: ""
webhookService:
  ports:
  - port: 443
    targetPort: 9443
  type: ClusterIP
