apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "operator-with-empty-nodeselector.fullname" . }}-pvc-lim
  labels:
  {{- include "operator-with-empty-nodeselector.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvcLim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.pvcLim.storageClass | quote }}