apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "operator-with-empty-nodeselector.fullname" . }}-serving-cert
  labels:
  {{- include "operator-with-empty-nodeselector.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "operator-with-empty-nodeselector.fullname" . }}-webhook-service.{{
    .Release.Namespace }}.svc'
  - '{{ include "operator-with-empty-nodeselector.fullname" . }}-webhook-service.{{
    .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "operator-with-empty-nodeselector.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert