apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-manager-aggregated-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: app.kubernetes.io/instance
      operator: In
      values:
      - my-operator
rules: []