apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "operator.fullname" . }}-pvc-lim
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvcLim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.pvcLim.storageClass | quote }}