apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-secret-ca
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
data:
  ca.crt: {{ required "secretCa.caCrt is required" .Values.secretCa.caCrt | b64enc
    | quote }}
type: opaque