apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-secret-ca
  labels:
  {{- include "operator.labels" . | nindent 4 }}
data:
  ca.crt: {{ tpl (required "secretCa.caCrt is required" .Values.secretCa.caCrt) $
    | b64enc | quote }}
type: opaque