apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-secret-vars
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
data:
  VAR1: {{ required "secretVars.var1 is required" .Values.secretVars.var1 | b64enc
    | quote }}
  VAR2: {{ required "secretVars.var2 is required" .Values.secretVars.var2 | b64enc
    | quote }}
type: opaque