apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "operator.fullname" . }}-serving-cert
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - my-operator-webhook-service.{{ .Release.Namespace }}.svc
  - my-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: '{{ include "operator.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert